import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DarkModeToggle from "@/components/DarkModeToggle/DarkModeToggle";
import {ThemeProvider} from "@/context/ThemeContext" 
import SessionWrapper from "@/components/SessionWrapper";  


const poppins = Poppins({ 
  subsets: ["latin"],
  variable: "--my-font-family",   
  weight: ["400", "500", "600", "700", "800", "900"]          
 });

export const metadata: Metadata = {
  title: "Lyrix",        
  description: "Generated by create next app",      
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {    
  return (
    <html lang="en">
      <body className={poppins.className}>    
        <ThemeProvider>  
          <SessionWrapper>   
          <DarkModeToggle/> 
          {children}      
          </SessionWrapper>
        </ThemeProvider>  
      </body> 
    </html>
  );
}       

